import type { Metadata } from "next";
import "./globals.css"
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Home / Library Management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="flex items-center justify-between px-4 bg-[#0a298c] py-2 text-white font-normal text-lg">
          <div className="flex gap-1 text-3xl font-semibold">
              <span>I</span>
              <span style={{transform: "rotateZ(-45deg)"}} className="text-red-500">C</span>
              <span>E</span>
            </div>
            <h2 className="text-center">Library Management</h2>
            <Navbar />
        </header>
        {children}
      </body>
    </html>
  );
}
